### ISSUE TITLE
Mechanism of Optimistic Lock version update

### ISSUE THREAD

**Issue by Jerry-Gren** [Deophius/singin#18]
Using Optimistic Lock means that the program doesn't need to lock the database to solve concurrency problems, and just by checking the version of Optimistic Lock, it can believe its data are "safe". However, things are not that simple.
Most of the programs we face today which uses the Optimistic Lock are so optimistic about its surroundings, and this is why we have a chance to rewrite the data even during card singin processes.
In GS's database we can easily figure out the way it works. Find `OptimisticLockField` and you'll see integer numbers as its value. You can take them as version numbers. If the database is not overwritten by our program, definitely they are monotonically increasing. 
Though GS pluses 1 to the version number every time it writes a record, GS doesn't seem to check whether the field is safe. But even if GS adds a verification process, it could be easily broken by other program. So I suggest that GS should strengthen its body, such as learning protection methods from a company called "XH"?

**Comment by Deophius** [comment]
I believe @Jerry-Gren has the point. Currently the `write_record()` function doesn't increment the `OptimisticLockField` and it didn't cause us any trouble. In fact, this can be used to check whose sign in was authentic and whose was done by our program.

If the GS do strengthen its data consistency checks in the future, hopefully this issue can point the future developers in the right way.

**Comment by Jerry-Gren** [comment]
This Issue should be closed because it will make **NO** contribution to this project in a short term.
Marked as Outdated.
