### ISSUE TITLE
Customize looks

### ISSUE THREAD

**Issue by Deophius** [Deophius/singin#5]
The current "visual publish" of the GS software is a little bit lousy.
Perhaps we can create a proxy server that feeds it information that will make it look better?
(Using python's `http-server` on port 80 seems like a bold idea to me)

**Comment by Deophius** [comment]
Now at the head of branch `proxy`, the UDP Handler creates a new socket every time it writes to the school server. This is obviously wrong, we need to use `self.server.socket` to do this.

**Comment by Jerry-Gren** [comment]
Hello, I'm one of the idea proposers of this project. We've encountered some crucial problems on our code, and it will be quite dangerous to continue using this code structure and language. So Deophius and I have decided to switch to another language and rewrite some of the code. The rebuilt edition should have a much better invisibility.
