### ISSUE TITLE
Code Rebuild

### ISSUE THREAD

**Issue by Jerry-Gren** [Deophius/singin#6]
Hello, I'm one of the idea proposers of this project. We've encountered some crucial problems on our code, and it will be quite dangerous to continue using **this** language and code structure. So Deophius and I have decided to **switch to another language and rewrite some of the code**. The rebuilt edition should have a much better invisibility.

**Comment by Deophius** [comment]
"Invisibility" sounds like a reallly good name to me :)

**Comment by Deophius** [comment]
By the way, using the code in `proxy` and `notif` branches is quite dangerous. We temporarily give up using a proxy server because that's the _root of all evil._ This should close #5.

**Comment by Deophius** [comment]
This issue will be resolved if #8 is merged.
